Repository brianegan/chewie, pull requests merged in 2020-11, with the labels that each got.

#391 feat(cupertino_controls): add new skip icons
  lib/src/cupertino_controls.dart
Labels: enhancement

#390 Playback speed controls
  lib/src/chewie_player.dart
  lib/src/cupertino_controls.dart
  lib/src/material_controls.dart
Labels: enhancement

#228 Show replay button if video completes for Android OS
  lib/src/cupertino_controls.dart
  lib/src/material_controls.dart
Labels: awaiting feedback

#355 Export controls in chewie.dart.
  lib/chewie.dart
Labels: bug
